### ISSUE TITLE
网站公告类型无法选择

### ISSUE THREAD

**Issue by penhuowa** [wangyiidii/jdx#11]
选择html却不生效，wxpusher只能推送账号是否生效还是也能推每天的资产？诺兰之前是青龙备注名是:备注@@时间戳@@UID，就可以完成推送以及账号失效提醒，凉了之后我又用的ccwav的推送通知，也能匹配这个格式，不知道这个是怎么弄的，

**Comment by TT-IPIP** [comment]
@@uid123456试试

**Comment by penhuowa** [comment]
> @@uid123456试试

我已经试过了，通知失效，还算不错，无感通知

**Comment by wangyiidii** [comment]
目前一对一的通知，只有JDX内置的Cookie检测有效性通知。其他的对接脚本的，需要后面加吧~
