### ISSUE TITLE
2.10.13版本的青龙变量只能新增，无法更新

### ISSUE THREAD

**Issue by ThatYears** [wangyiidii/jdx#16]
我不晓得是跟青龙版本有关，还是变量里的pt_pin是中文转码的有关。在2.10.13版本的青龙里，我试过不填备注，填备注都无法更新，只会新增一个新的变量。是什么原因？还望赐教

**Comment by my11712** [comment]
2.10.3版本青龙更新环境变量参数从id改为了:_id,需要更新

**Comment by ThatYears** [comment]
那看来只能等更新，如果能根据青龙版本适配下就好了

**Comment by wangyiidii** [comment]
0.2.0之后已经兼容

**Comment by ThatYears** [comment]
不是版本的原因，那是什么原因导致的？我用的docker 0.8 的版本。pt_pin是中文URL编码的原因导致的么？
