### ISSUE TITLE
刷新青龙Token定时任务太快,一分钟刷新一次青龙token,无必要

### ISSUE THREAD

**Issue by my11712** [wangyiidii/jdx#18]
QLService.class 

 scheduleTaskUtil.startCron("QL_timerRefreshToken", () -> this.timerRefreshToken(), "0 0/1 * * * ?");
一分钟刷新一次青龙token太快了。在获取青龙token返回参数中有 expiration字段时间戳,表示失效时间

**Comment by wangyiidii** [comment]
嗯 多谢提供
