### ISSUE TITLE
程序能正常获取短信，点击提交后，弹出获取CK成功，并无出现CK

### ISSUE THREAD

**Issue by 1274326018** [wangyiidii/jdx#3]

**Comment by wangyiidii** [comment]
提交青龙模式下不弹出复制CK的弹框

**Comment by 1274326018** [comment]
![image](https://user-images.githubusercontent.com/71999976/155253379-e14e27e1-8a7e-49f0-9d2b-222978f9f16f.png)

**Comment by 1274326018** [comment]
![image](https://user-images.githubusercontent.com/71999976/155253379-e14e27e1-8a7e-49f0-9d2b-222978f9f16f.png)

**Comment by wangyiidii** [comment]
有疑问的话可以留下网站或者联系方式（推荐），我看下
