### ISSUE TITLE
QL配置只能删除和新增，不能编辑操作

### ISSUE THREAD

**Issue by flylufly** [wangyiidii/jdx#7]
请问大佬，这个能添加更新操作么，对于很多过期的CK如果能自动更新失效的CK是非常有用的功能，希望大佬在后续版本中增加相关功能，对已有的CK进行更新操作

**Comment by wangyiidii** [comment]
更新QL配置？

**Comment by wangyiidii** [comment]
1. 就是通过JDX获取的pt_pin是中文的还是转码后的？
2. 提交至QL的正确的pt_pin应该是中文的还是转码后的？

**Comment by qxq498042034** [comment]
这个我在论坛有回复过
1.jdx获取的pt_pin是中文的，没转码。
2.提交至QL中文和转码后的都是可以的，都能正常提交，但中文未转码的pt_pin会判定为新的账号，而不是覆盖原来的旧账号。另外部分脚本如果pt_pin是中文运行会报错。

**Comment by flylufly** [comment]
不知道更新的CK会不会我更新时间，目前布置后原有的CK更新后不会更新时间，禁用的没有测试不会自动启动，

**Comment by flylufly** [comment]
我在原有有效的CK，使用更新后提交，在环境变量中，时间和备注都不会被更改，不知道是否被更新成功

**Comment by flylufly** [comment]
我删除了原有有效CK，JDX提交后会有个新的CK，备注也是我提交的，但是时间并未更新，还是原来的时间，我的是2.11版本青龙

**Comment by qxq498042034** [comment]
我觉得你可能并没有提交成功，因为我实测下来，时间是会更新的，禁用的账号也会自动启用，备注的话0.1.4之前不修改备注会自动填入手机号，更新后原本有有备注的，在没填写备注的情况下是不进行修改的，作者这点写的还是很清楚的

**Comment by flylufly** [comment]
或者你们测试青龙2.11.2了么？

**Comment by qxq498042034** [comment]
我大版本还在2.10.x

**Comment by flylufly** [comment]
有空我看看新建立的2.11.2会怎么样，可能青龙接口改变了

**Comment by wangyiidii** [comment]
下个版本

**Comment by flylufly** [comment]
> 下个版本

请问大佬试过2.11.2版本一切正常么？

**Comment by wangyiidii** [comment]
没有呢，等有空升级看看吧。我还在2.9
