### ISSUE TITLE
社交平台怎么填

### ISSUE THREAD

**Issue by penhuowa** [wangyiidii/jdx#9]
大佬社交平台应用这一项看不懂啊，这个具体是干什么的？不会设置

**Comment by flylufly** [comment]
可以在GITEE或者GITHUB设置三方应用用于登录后台，下边说明说的已经很明确了

**Comment by TT-IPIP** [comment]
> 可以在GITEE或者GITHUB设置三方应用用于登录后台，下边说明说的已经很明确了

应用主页 *
应用回调地址 * 
填什么

**Comment by penhuowa** [comment]
说实话不太懂，主要是干什么的不懂，按照说明填一下看看

**Comment by TT-IPIP** [comment]
应用主页 *
应用回调地址 *
不知道这么填

存在错误
无效的登录回调地址

**Comment by wangyiidii** [comment]
**害  算了，还是写个登录框吧。。。本来想着这样一劳永逸，结果都不会**

**Comment by penhuowa** [comment]
> **害 算了，还是写个登录框吧。。。本来想着这样一劳永逸，结果都不会**

感谢大佬，建个群组吧，小白还是太多

**Comment by TT-IPIP** [comment]
> 应用主页 *
> 应用回调地址 *
这 怎么写

**Comment by feiniao025** [comment]
佬什么时候出个ARM版本的

**Comment by wangyiidii** [comment]
移除了社交登录，改成用户名密码登录
